"""
Aegis AI — Health Insurance Plan Catalog
Complete internal plan registry for Sarah AI.
Nine plans across three customer segments.
"""

# ── Segment thresholds (monthly budget in INR) ────────────────────────────────
SEGMENT_THRESHOLDS = {
    "budget":   (0,     1200),   # < ₹1,200/month
    "standard": (1200,  3500),   # ₹1,200 – ₹3,500/month
    "premium":  (3500,  999999), # > ₹3,500/month
}

SEGMENT_LABELS = {
    "budget":   "Budget",
    "standard": "Standard",
    "premium":  "Premium",
}

# ── Plan catalog ──────────────────────────────────────────────────────────────

HEALTH_PLANS = {

    # ════════════════════════════════════════════════════════════════════════
    # BUDGET SEGMENT
    # ════════════════════════════════════════════════════════════════════════

    "basic_care_shield": {
        "plan_id":            "AEG-HLT-001",
        "plan_name":          "Basic Care Shield",
        "segment":            "budget",
        "coverage_amount":    400_000,
        "coverage_display":   "₹4,00,000",
        "premium_min":        380,
        "premium_max":        540,
        "cashless_hospitals": "5,000+",
        "room_rent":          "₹2,000/day",
        "icu":                "₹4,000/day",
        "day_care":           "300+ procedures",
        "ped_waiting":        "4 years",
        "ncb":                "20% per year (max 40%)",
        "health_checkup":     "Every 2 years",
        "maternity":          "Not covered",
        "critical_illness":   "Not covered",
        "ambulance":          "₹2,000/hospitalisation",
        "restoration":        "Not included",
        "opd":                "Not included",
        "claim_process":      "Cashless + Reimbursement",
        "claim_ratio":        "97.2%",
        "eligibility":        "3 months – 65 years",
        "co_payment":         "10% if age > 60",
        "benefits": [
            "Cashless hospitalisation at 5,000+ hospitals",
            "Covers 300+ day-care procedures",
            "20% No Claim Bonus per year",
            "Pre and post hospitalisation: 30 / 60 days",
            "Annual health check-up (every 2 years)",
        ],
        "exclusions": [
            "Cosmetic or aesthetic treatment",
            "Pre-existing diseases (first 4 years)",
            "Self-inflicted injuries",
            "Non-allopathic treatment",
        ],
        "suitable_for": [
            "First-time insurance buyers",
            "Young individuals or couples",
            "Very tight budget",
        ],
        "risk_level": "Low Risk",
    },

    "essential_care_plus": {
        "plan_id":            "AEG-HLT-002",
        "plan_name":          "Essential Care Plus",
        "segment":            "budget",
        "coverage_amount":    750_000,
        "coverage_display":   "₹7,50,000",
        "premium_min":        540,
        "premium_max":        780,
        "cashless_hospitals": "8,000+",
        "room_rent":          "₹3,000/day",
        "icu":                "₹6,000/day",
        "day_care":           "All 541 listed procedures",
        "ped_waiting":        "3 years",
        "ncb":                "25% per year (max 50%)",
        "health_checkup":     "Annual",
        "maternity":          "Not covered",
        "critical_illness":   "Not covered",
        "ambulance":          "₹3,000/hospitalisation",
        "restoration":        "50% of base sum insured (once per year)",
        "opd":                "Not included",
        "claim_process":      "Cashless + Reimbursement",
        "claim_ratio":        "97.9%",
        "eligibility":        "3 months – 65 years",
        "co_payment":         "Nil",
        "benefits": [
            "₹7.5L coverage across all hospitalisations",
            "Cashless at 8,000+ empanelled hospitals",
            "50% restoration of sum insured once per year",
            "All 541 day-care procedures covered",
            "Annual health check-up included",
            "25% NCB compounding per claim-free year",
        ],
        "exclusions": [
            "Pre-existing diseases (first 3 years)",
            "Maternity and newborn expenses",
            "Dental treatment (unless accidental)",
        ],
        "suitable_for": [
            "Small family (2–3 members)",
            "No pre-existing conditions",
            "Moderate coverage needs",
        ],
        "risk_level": "Low Risk",
    },

    "value_guard_plan": {
        "plan_id":            "AEG-HLT-003",
        "plan_name":          "Value Guard",
        "segment":            "budget",
        "coverage_amount":    1_000_000,
        "coverage_display":   "₹10,00,000",
        "premium_min":        780,
        "premium_max":        1100,
        "cashless_hospitals": "10,000+",
        "room_rent":          "Single standard AC room",
        "icu":                "No sublimit",
        "day_care":           "All 541 procedures",
        "ped_waiting":        "3 years",
        "ncb":                "30% per year (max 50%)",
        "health_checkup":     "Annual (family)",
        "maternity":          "After 2 years (up to ₹30,000)",
        "critical_illness":   "Not covered",
        "ambulance":          "₹5,000/hospitalisation",
        "restoration":        "100% sum insured once per year",
        "opd":                "Not included",
        "claim_process":      "Cashless + Reimbursement",
        "claim_ratio":        "98.1%",
        "eligibility":        "3 months – 65 years",
        "co_payment":         "Nil",
        "benefits": [
            "₹10L coverage with full restoration benefit",
            "Cashless access at 10,000+ hospitals",
            "100% restoration of sum insured annually",
            "Standard AC room — no limit on ICU charges",
            "Maternity cover after 2 years",
            "Annual family health check-up",
        ],
        "exclusions": [
            "Pre-existing diseases (first 3 years)",
            "Specific disease waiting period: 2 years",
            "Non-allopathic treatment",
        ],
        "suitable_for": [
            "Families of 3–4 with moderate risk",
            "Seeking ₹10L at controlled premium",
            "No major pre-existing conditions",
        ],
        "risk_level": "Low Risk",
    },

    # ════════════════════════════════════════════════════════════════════════
    # STANDARD SEGMENT
    # ════════════════════════════════════════════════════════════════════════

    "standard_protect": {
        "plan_id":            "AEG-HLT-004",
        "plan_name":          "Standard Protect",
        "segment":            "standard",
        "coverage_amount":    1_000_000,
        "coverage_display":   "₹10,00,000",
        "premium_min":        1050,
        "premium_max":        1500,
        "cashless_hospitals": "12,000+",
        "room_rent":          "Single standard AC room",
        "icu":                "No sublimit",
        "day_care":           "All 541 procedures",
        "ped_waiting":        "2 years",
        "ncb":                "35% per year (max 50%)",
        "health_checkup":     "Annual",
        "maternity":          "After 2 years (up to ₹50,000)",
        "critical_illness":   "₹1,00,000 lump sum",
        "ambulance":          "₹7,500/hospitalisation",
        "restoration":        "100% sum insured once per year",
        "opd":                "Not included",
        "claim_process":      "Cashless + Reimbursement",
        "claim_ratio":        "98.4%",
        "eligibility":        "3 months – 65 years",
        "co_payment":         "Nil",
        "benefits": [
            "₹10L coverage with 2-year PED waiver",
            "Cashless at 12,000+ empanelled hospitals",
            "Critical illness lump sum: ₹1,00,000",
            "100% restoration annually",
            "35% NCB compounding",
            "Pre and post hospitalisation: 60 / 90 days",
        ],
        "exclusions": [
            "Pre-existing diseases (first 2 years)",
            "Dental and vision unless accidental",
            "Experimental or unproven treatments",
        ],
        "suitable_for": [
            "Families of 3–4 with moderate income",
            "No major pre-existing conditions",
            "Looking for ₹10L at mid-range premium",
        ],
        "risk_level": "Low Risk",
    },

    "family_shield": {
        "plan_id":            "AEG-HLT-005",
        "plan_name":          "Family Shield",
        "segment":            "standard",
        "coverage_amount":    1_500_000,
        "coverage_display":   "₹15,00,000",
        "premium_min":        1500,
        "premium_max":        2200,
        "cashless_hospitals": "12,000+",
        "room_rent":          "No sublimit",
        "icu":                "No sublimit",
        "day_care":           "All 541 procedures",
        "ped_waiting":        "2 years",
        "ncb":                "40% per year (max 50%)",
        "health_checkup":     "Annual (all members)",
        "maternity":          "Yes — after 2 years (₹75,000 + newborn cover)",
        "critical_illness":   "₹2,00,000 lump sum",
        "ambulance":          "₹10,000/hospitalisation + air ambulance",
        "restoration":        "100% unlimited restoration",
        "opd":                "Not included",
        "claim_process":      "Cashless + Reimbursement",
        "claim_ratio":        "98.6%",
        "eligibility":        "3 months – 65 years",
        "co_payment":         "Nil",
        "benefits": [
            "₹15L with no room rent or ICU sublimits",
            "Unlimited restoration — as many times as needed",
            "Maternity + newborn cover after 2 years",
            "Critical illness: ₹2L lump sum",
            "Air ambulance cover included",
            "40% NCB per claim-free year",
            "Annual health check-up for all members",
        ],
        "exclusions": [
            "Pre-existing diseases (first 2 years)",
            "Adventure sports injuries",
            "Non-empanelled hospital (reimbursement path)",
        ],
        "suitable_for": [
            "Families of 4–5 with children",
            "Planning for maternity in 2 years",
            "Comprehensive family protection priority",
        ],
        "risk_level": "Low Risk",
    },

    "complete_care": {
        "plan_id":            "AEG-HLT-006",
        "plan_name":          "Complete Care",
        "segment":            "standard",
        "coverage_amount":    2_500_000,
        "coverage_display":   "₹25,00,000",
        "premium_min":        2200,
        "premium_max":        3200,
        "cashless_hospitals": "12,500+",
        "room_rent":          "No sublimit",
        "icu":                "No sublimit",
        "day_care":           "All procedures",
        "ped_waiting":        "1 year",
        "ncb":                "50% per year (max 100%)",
        "health_checkup":     "Annual comprehensive (all members)",
        "maternity":          "Yes — after 1 year (₹1,00,000 + newborn vaccination)",
        "critical_illness":   "₹3,00,000 lump sum",
        "ambulance":          "₹15,000 + air ambulance",
        "restoration":        "200% annually (2x base sum insured)",
        "opd":                "₹5,000/year",
        "claim_process":      "Cashless + Reimbursement + Digital",
        "claim_ratio":        "98.9%",
        "eligibility":        "3 months – 70 years",
        "co_payment":         "Nil",
        "benefits": [
            "₹25L with 1-year PED waiver",
            "200% restoration — double cover annually",
            "Maternity + newborn + vaccination cover",
            "Critical illness: ₹3L lump sum",
            "OPD cover: ₹5,000/year",
            "50% NCB compounding (up to 100%)",
            "Comprehensive annual health check-up",
            "Air ambulance + road ambulance",
        ],
        "exclusions": [
            "Pre-existing diseases (first 1 year)",
            "Dental and vision unless accidental",
        ],
        "suitable_for": [
            "Families with growing children",
            "Maternity planning",
            "Mid-to-high income seeking top-tier standard coverage",
        ],
        "risk_level": "Low Risk",
    },

    # ════════════════════════════════════════════════════════════════════════
    # PREMIUM SEGMENT
    # ════════════════════════════════════════════════════════════════════════

    "premium_elite": {
        "plan_id":            "AEG-HLT-007",
        "plan_name":          "Premium Elite",
        "segment":            "premium",
        "coverage_amount":    5_000_000,
        "coverage_display":   "₹50,00,000",
        "premium_min":        3500,
        "premium_max":        5200,
        "cashless_hospitals": "15,000+ (including international)",
        "room_rent":          "No sublimit (any category)",
        "icu":                "No sublimit",
        "day_care":           "All procedures",
        "ped_waiting":        "Immediate (day 1 for listed conditions)",
        "ncb":                "50% per year + Super NCB bonus",
        "health_checkup":     "Annual executive check-up (₹15,000 value)",
        "maternity":          "Yes — immediate (₹1,50,000 + NICU cover)",
        "critical_illness":   "₹10,00,000 lump sum (34 illnesses)",
        "ambulance":          "Air ambulance (domestic)",
        "restoration":        "Unlimited",
        "opd":                "₹15,000/year + specialist consultations",
        "claim_process":      "Cashless + Reimbursement + Dedicated Relationship Manager",
        "claim_ratio":        "99.1%",
        "eligibility":        "91 days – 75 years",
        "co_payment":         "Nil",
        "benefits": [
            "₹50L coverage with unlimited restoration",
            "Immediate day-1 coverage for listed pre-existing conditions",
            "Critical illness cover: ₹10L for 34 illnesses",
            "International cashless at 15,000+ hospitals",
            "Air ambulance (domestic) included",
            "Premium maternity + NICU cover",
            "OPD: ₹15,000/year + specialist visits",
            "Dedicated Relationship Manager for claims",
            "Executive annual health check-up",
        ],
        "exclusions": [
            "Unlisted pre-existing diseases (first 30 days)",
            "Experimental treatments",
        ],
        "suitable_for": [
            "High-income families",
            "Pre-existing conditions requiring early cover",
            "Executives requiring premium healthcare access",
        ],
        "risk_level": "Low Risk",
    },

    "executive_shield": {
        "plan_id":            "AEG-HLT-008",
        "plan_name":          "Executive Shield",
        "segment":            "premium",
        "coverage_amount":    10_000_000,
        "coverage_display":   "₹1,00,00,000",
        "premium_min":        5500,
        "premium_max":        8500,
        "cashless_hospitals": "20,000+ worldwide",
        "room_rent":          "No sublimit (presidential suite permitted)",
        "icu":                "No sublimit",
        "day_care":           "All procedures",
        "ped_waiting":        "Immediate (all conditions)",
        "ncb":                "100% per year (doubles every 2 years)",
        "health_checkup":     "Bi-annual executive + specialist consultation",
        "maternity":          "International maternity (₹3,00,000 + NICU)",
        "critical_illness":   "₹25,00,000 lump sum (54 illnesses)",
        "ambulance":          "Air ambulance worldwide",
        "restoration":        "Unlimited worldwide",
        "opd":                "₹30,000/year + mental health sessions",
        "claim_process":      "Cashless + Priority Claims Desk + Legal Support",
        "claim_ratio":        "99.4%",
        "eligibility":        "91 days – 80 years",
        "co_payment":         "Nil",
        "benefits": [
            "₹1 Crore coverage — worldwide",
            "Immediate cover for ALL pre-existing conditions",
            "Critical illness: ₹25L (54 conditions)",
            "International air ambulance",
            "Mental health + OPD: ₹30,000/year",
            "International maternity cover",
            "100% NCB doubling every 2 claim-free years",
            "Priority Claims Desk + Legal assistance",
            "Bi-annual executive health check-up",
        ],
        "exclusions": [
            "Cosmetic and aesthetic procedures",
            "Self-inflicted harm",
        ],
        "suitable_for": [
            "Senior executives, HNIs",
            "Global lifestyle requiring international cover",
            "Family with critical illness history",
        ],
        "risk_level": "Very Low Risk",
    },

    "platinum_protect": {
        "plan_id":            "AEG-HLT-009",
        "plan_name":          "Platinum Protect",
        "segment":            "premium",
        "coverage_amount":    20_000_000,
        "coverage_display":   "₹2,00,00,000",
        "premium_min":        9500,
        "premium_max":        15000,
        "cashless_hospitals": "Unlimited — any hospital worldwide",
        "room_rent":          "No sublimit globally",
        "icu":                "No sublimit globally",
        "day_care":           "All procedures globally",
        "ped_waiting":        "None — immediate full coverage",
        "ncb":                "200% per year (up to 4x base)",
        "health_checkup":     "Quarterly preventive + annual executive",
        "maternity":          "Premium global maternity (₹5,00,000 + all newborn cover)",
        "critical_illness":   "₹50,00,000 lump sum (76 illnesses)",
        "ambulance":          "Premium air ambulance + medical escort",
        "restoration":        "Unlimited globally (no cap)",
        "opd":                "₹60,000/year + dental + vision",
        "claim_process":      "Cashless + White-Glove Claims Concierge + 4-hour settlement",
        "claim_ratio":        "99.7%",
        "eligibility":        "Any age (new-born to lifetime)",
        "co_payment":         "Nil — zero out-of-pocket",
        "benefits": [
            "₹2 Crore coverage — anywhere in the world",
            "Zero waiting period — cover starts day 1",
            "Critical illness: ₹50L (76 conditions)",
            "Dental + Vision included in OPD package",
            "4-hour claims settlement SLA",
            "Quarterly preventive health monitoring",
            "Premium global maternity + newborn",
            "Medical escort + air ambulance",
            "200% NCB compounding annually",
            "Concierge claims team available 24/7",
        ],
        "exclusions": [
            "Purely cosmetic procedures",
            "Self-inflicted harm",
        ],
        "suitable_for": [
            "Ultra-HNIs requiring global unlimited coverage",
            "No tolerance for any gap in coverage",
            "Multi-country lifestyle",
        ],
        "risk_level": "Ultra Low Risk",
    },
}

# Quick lookup by segment
PLANS_BY_SEGMENT = {
    "budget":   ["basic_care_shield", "essential_care_plus", "value_guard_plan"],
    "standard": ["standard_protect", "family_shield", "complete_care"],
    "premium":  ["premium_elite",    "executive_shield",    "platinum_protect"],
}
