"""
Aegis AI — Property Insurance Plan Catalog
Complete internal plan registry for Emma AI.
Nine plans across three customer segments covering residential and commercial property.
"""

# ── Property type classification ──────────────────────────────────────────────

PROPERTY_CATEGORIES = {
    "apartment":          ["apartment", "flat", "floor", "condo", "condominium", "society",
                           "complex", "bhk", "studio", "1bhk", "2bhk", "3bhk", "4bhk"],
    "independent_house":  ["house", "bungalow", "duplex", "row house", "rowhouse", "plot",
                           "independent", "detached", "kothi", "individual house"],
    "villa":              ["villa", "farmhouse", "penthouse", "mansion", "luxury home",
                           "estate", "compound"],
    "commercial_building":["commercial building", "multi-storey commercial", "business park",
                           "corporate building", "commercial complex"],
    "office":             ["office", "coworking", "workspace", "co-working", "serviced office"],
    "shop":               ["shop", "store", "retail", "showroom", "boutique", "kirana",
                           "restaurant", "café", "bakery", "salon"],
    "warehouse":          ["warehouse", "godown", "storage", "depot", "cold storage", "logistics"],
    "factory":            ["factory", "manufacturing", "plant", "industrial", "workshop",
                           "production unit", "assembly"],
    "agricultural":       ["farm", "agricultural", "barn", "shed", "crop storage",
                           "poultry", "dairy"],
    "rental_property":    ["rental", "rented", "tenant", "paying guest", "pg", "hostel",
                           "lodge", "guesthouse"],
}

# ── Segment thresholds (annual premium budget in INR) ─────────────────────────

SEGMENT_THRESHOLDS = {
    "budget":   (0,      6_000),    # < ₹6,000/year
    "standard": (6_000,  18_000),   # ₹6,000 – ₹18,000/year
    "premium":  (18_000, 999_999),  # > ₹18,000/year
}

# ── Property plan catalog ──────────────────────────────────────────────────────

PROPERTY_PLANS = {

    # ══════════════════════════════════════════════════════════════════════════
    # BUDGET SEGMENT
    # ══════════════════════════════════════════════════════════════════════════

    "home_essential": {
        "plan_id":               "AEG-PROP-001",
        "plan_name":             "Home Essential",
        "segment":               "budget",

        # Coverage
        "structure_coverage":    1_500_000,
        "structure_display":     "₹15,00,000",
        "contents_coverage":     300_000,
        "contents_display":      "₹3,00,000",
        "coverage_display":      "₹15L Structure + ₹3L Contents",

        # Premium (annual)
        "premium_min":           1_200,
        "premium_max":           2_200,
        "premium_period":        "annual",

        # Core covers
        "fire_cover":            True,
        "fire_detail":           "Structure only, rebuild cost basis",
        "flood_cover":           False,
        "flood_detail":          "Not included",
        "earthquake_cover":      False,
        "earthquake_detail":     "Not included",
        "storm_cover":           False,
        "storm_detail":          "Not included",
        "theft_cover":           True,
        "theft_sublimit":        "₹50,000",
        "temp_accommodation":    False,
        "temp_accommodation_detail": "Not included",
        "electrical_cover":      False,
        "electrical_detail":     "Not included",
        "glass_cover":           False,
        "glass_detail":          "Not included",
        "public_liability":      False,
        "rental_income":         False,
        "jewelry_cover":         False,
        "all_risk_contents":     False,
        "accidental_damage":     False,

        # Quality
        "claim_process":         "Standard reimbursement — 15 working days",
        "claim_ratio":           "96.8%",
        "eligibility":           "Residential properties up to 30 years old",
        "benefits": [
            "Fire and explosion cover for structure up to ₹15L",
            "Basic theft and burglary cover (₹50,000 sublimit)",
            "Contents cover up to ₹3,00,000",
            "Lightning, riot, and strike damage included",
            "Annual renewal with premium stability guarantee",
        ],
        "exclusions": [
            "Flood and earthquake not covered",
            "Structural defects and poor maintenance",
            "Commercial activity from home",
            "Vacant property beyond 30 days",
        ],
        "suitable_for": [
            "First-time property insurance buyers",
            "Rental apartments in low-risk zones",
            "Low-value properties with basic protection needs",
        ],
    },

    "home_secure": {
        "plan_id":               "AEG-PROP-002",
        "plan_name":             "Home Secure",
        "segment":               "budget",

        "structure_coverage":    2_500_000,
        "structure_display":     "₹25,00,000",
        "contents_coverage":     500_000,
        "contents_display":      "₹5,00,000",
        "coverage_display":      "₹25L Structure + ₹5L Contents",

        "premium_min":           2_200,
        "premium_max":           4_000,
        "premium_period":        "annual",

        "fire_cover":            True,
        "fire_detail":           "Structure + contents, rebuild cost basis",
        "flood_cover":           True,
        "flood_detail":          "Up to ₹5,00,000 (structure only)",
        "earthquake_cover":      True,
        "earthquake_detail":     "Up to ₹5,00,000 (structure only)",
        "storm_cover":           True,
        "storm_detail":          "Cyclone, storm, tempest — structure only",
        "theft_cover":           True,
        "theft_sublimit":        "₹1,00,000",
        "temp_accommodation":    True,
        "temp_accommodation_detail": "₹5,000/week up to 4 weeks",
        "electrical_cover":      False,
        "electrical_detail":     "Not included",
        "glass_cover":           False,
        "glass_detail":          "Not included",
        "public_liability":      False,
        "rental_income":         False,
        "jewelry_cover":         False,
        "all_risk_contents":     False,
        "accidental_damage":     False,

        "claim_process":         "Cashless repair + reimbursement — 12 working days",
        "claim_ratio":           "97.2%",
        "eligibility":           "Residential properties up to 35 years old",
        "benefits": [
            "Structure cover ₹25L + contents ₹5L",
            "Flood and earthquake cover up to ₹5L each",
            "Cyclone and storm damage included",
            "Theft cover up to ₹1,00,000",
            "Temporary accommodation: ₹5,000/week × 4 weeks",
            "Lightning, explosion, riot, strike included",
        ],
        "exclusions": [
            "Electrical damage not covered",
            "Jewelry and valuables above ₹50,000",
            "Structural defects or faulty construction",
            "Properties beyond 35 years without inspection",
        ],
        "suitable_for": [
            "Apartments and houses in moderate-risk zones",
            "Properties near water bodies or cyclone-prone coast",
            "Budget-conscious owners wanting natural calamity protection",
        ],
    },

    "home_value": {
        "plan_id":               "AEG-PROP-003",
        "plan_name":             "Home Value",
        "segment":               "budget",

        "structure_coverage":    4_000_000,
        "structure_display":     "₹40,00,000",
        "contents_coverage":     800_000,
        "contents_display":      "₹8,00,000",
        "coverage_display":      "₹40L Structure + ₹8L Contents",

        "premium_min":           4_000,
        "premium_max":           6_000,
        "premium_period":        "annual",

        "fire_cover":            True,
        "fire_detail":           "Full replacement cost — structure and contents",
        "flood_cover":           True,
        "flood_detail":          "Up to ₹10,00,000",
        "earthquake_cover":      True,
        "earthquake_detail":     "Up to ₹10,00,000",
        "storm_cover":           True,
        "storm_detail":          "Cyclone, storm, hail — structure and contents",
        "theft_cover":           True,
        "theft_sublimit":        "₹1,50,000 (cash ₹25,000 sublimit)",
        "temp_accommodation":    True,
        "temp_accommodation_detail": "₹10,000/week up to 8 weeks",
        "electrical_cover":      True,
        "electrical_detail":     "Up to ₹25,000 for surge and short circuit",
        "glass_cover":           True,
        "glass_detail":          "Fixed glass panels — replacement cost",
        "public_liability":      False,
        "rental_income":         False,
        "jewelry_cover":         False,
        "all_risk_contents":     False,
        "accidental_damage":     False,

        "claim_process":         "Cashless empanelled contractors + reimbursement — 10 working days",
        "claim_ratio":           "97.5%",
        "eligibility":           "Residential properties up to 40 years old",
        "benefits": [
            "Structure ₹40L + contents ₹8L on replacement cost basis",
            "Full fire, flood, earthquake, storm package",
            "Electrical surge and short circuit cover up to ₹25,000",
            "Glass cover for fixed panels",
            "Temporary accommodation: ₹10,000/week × 8 weeks",
            "Theft including cash (₹25,000 sublimit)",
        ],
        "exclusions": [
            "Jewelry and artwork above ₹50,000 (no scheduled valuables cover)",
            "Public liability and legal expenses",
            "Properties beyond 40 years without structural certificate",
        ],
        "suitable_for": [
            "Mid-size apartments or row houses",
            "Properties with moderate contents value",
            "Owners seeking comprehensive natural calamity cover on a budget",
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # STANDARD SEGMENT
    # ══════════════════════════════════════════════════════════════════════════

    "home_protect": {
        "plan_id":               "AEG-PROP-004",
        "plan_name":             "Home Protect",
        "segment":               "standard",

        "structure_coverage":    5_000_000,
        "structure_display":     "₹50,00,000",
        "contents_coverage":     1_500_000,
        "contents_display":      "₹15,00,000",
        "coverage_display":      "₹50L Structure + ₹15L Contents",

        "premium_min":           5_500,
        "premium_max":           8_500,
        "premium_period":        "annual",

        "fire_cover":            True,
        "fire_detail":           "Full replacement cost with consequential loss cover",
        "flood_cover":           True,
        "flood_detail":          "Up to sum insured (structure + contents)",
        "earthquake_cover":      True,
        "earthquake_detail":     "Up to sum insured",
        "storm_cover":           True,
        "storm_detail":          "Cyclone, storm, hail, landslide — full cover",
        "theft_cover":           True,
        "theft_sublimit":        "₹2,00,000 (with first-loss settlement)",
        "temp_accommodation":    True,
        "temp_accommodation_detail": "₹15,000/week up to 12 weeks",
        "electrical_cover":      True,
        "electrical_detail":     "Up to ₹50,000 for surge, short circuit, lightning-induced damage",
        "glass_cover":           True,
        "glass_detail":          "All fixed glass + sanitary fittings",
        "public_liability":      True,
        "public_liability_detail": "Third-party bodily injury or property damage: ₹5,00,000",
        "rental_income":         False,
        "jewelry_cover":         False,
        "all_risk_contents":     False,
        "accidental_damage":     False,

        "claim_process":         "Cashless empanelled contractors + dedicated surveyor — 7 working days",
        "claim_ratio":           "98.0%",
        "eligibility":           "Residential and small commercial up to 45 years old",
        "benefits": [
            "₹50L structure + ₹15L contents — replacement cost",
            "Full natural calamity package (fire, flood, earthquake, storm, landslide)",
            "Third-party public liability: ₹5,00,000",
            "Electrical surge and short-circuit cover: ₹50,000",
            "Temporary accommodation: ₹15,000/week × 12 weeks",
            "All fixed glass and sanitary fittings included",
            "7-day claim settlement with dedicated surveyor",
        ],
        "exclusions": [
            "Jewelry and valuables (no scheduled articles cover)",
            "Rental income loss",
            "Deliberate damage or negligence",
        ],
        "suitable_for": [
            "2–3 BHK apartments or independent houses in urban areas",
            "Small business owners with combined home + office",
            "Properties in moderate flood or earthquake zones",
        ],
    },

    "family_property_shield": {
        "plan_id":               "AEG-PROP-005",
        "plan_name":             "Family Property Shield",
        "segment":               "standard",

        "structure_coverage":    7_500_000,
        "structure_display":     "₹75,00,000",
        "contents_coverage":     2_500_000,
        "contents_display":      "₹25,00,000",
        "coverage_display":      "₹75L Structure + ₹25L Contents",

        "premium_min":           8_500,
        "premium_max":           13_000,
        "premium_period":        "annual",

        "fire_cover":            True,
        "fire_detail":           "Full replacement cost + debris removal",
        "flood_cover":           True,
        "flood_detail":          "Full sum insured coverage",
        "earthquake_cover":      True,
        "earthquake_detail":     "Full sum insured coverage",
        "storm_cover":           True,
        "storm_detail":          "Cyclone, tempest, flood, landslide, rockslide",
        "theft_cover":           True,
        "theft_sublimit":        "₹3,00,000 (first-loss settlement)",
        "temp_accommodation":    True,
        "temp_accommodation_detail": "₹20,000/week up to 16 weeks",
        "electrical_cover":      True,
        "electrical_detail":     "₹1,00,000 — surge, short-circuit, arcing damage",
        "glass_cover":           True,
        "glass_detail":          "All glass including decorative panels",
        "public_liability":      True,
        "public_liability_detail": "Third-party liability: ₹10,00,000",
        "rental_income":         True,
        "rental_income_detail":  "Lost rental income: up to 6 months",
        "jewelry_cover":         True,
        "jewelry_detail":        "Scheduled jewelry and valuables: ₹5,00,000",
        "all_risk_contents":     False,
        "accidental_damage":     False,

        "claim_process":         "Cashless network + priority surveyor team — 5 working days",
        "claim_ratio":           "98.4%",
        "eligibility":           "Residential and commercial properties up to 50 years",
        "benefits": [
            "₹75L structure + ₹25L contents on replacement cost",
            "Complete natural calamity shield — fire, flood, earthquake, storm",
            "Rental income protection: up to 6 months",
            "Jewelry and valuables: ₹5,00,000 scheduled cover",
            "Third-party public liability: ₹10,00,000",
            "Electrical damage: ₹1,00,000",
            "Temporary accommodation: ₹20,000/week × 16 weeks",
            "Debris removal and professional fees included",
        ],
        "exclusions": [
            "All-risk contents (accidental damage) not included",
            "Properties under construction",
            "War and nuclear perils",
        ],
        "suitable_for": [
            "Large families in independent houses or villas",
            "Landlords with rental income to protect",
            "Properties with significant jewelry and valuables",
        ],
    },

    "complete_property_care": {
        "plan_id":               "AEG-PROP-006",
        "plan_name":             "Complete Property Care",
        "segment":               "standard",

        "structure_coverage":    10_000_000,
        "structure_display":     "₹1,00,00,000",
        "contents_coverage":     3_500_000,
        "contents_display":      "₹35,00,000",
        "coverage_display":      "₹1 Crore Structure + ₹35L Contents",

        "premium_min":           13_000,
        "premium_max":           18_000,
        "premium_period":        "annual",

        "fire_cover":            True,
        "fire_detail":           "Full replacement cost + loss of rent during reinstatement",
        "flood_cover":           True,
        "flood_detail":          "Full sum insured",
        "earthquake_cover":      True,
        "earthquake_detail":     "Full sum insured",
        "storm_cover":           True,
        "storm_detail":          "All natural calamities including cloudbursts",
        "theft_cover":           True,
        "theft_sublimit":        "₹5,00,000 (full first-loss basis)",
        "temp_accommodation":    True,
        "temp_accommodation_detail": "₹25,000/week up to 6 months",
        "electrical_cover":      True,
        "electrical_detail":     "₹2,00,000 — all electrical machinery and installations",
        "glass_cover":           True,
        "glass_detail":          "All glass, mirrors, ceramic tiles",
        "public_liability":      True,
        "public_liability_detail": "Personal liability: ₹25,00,000",
        "rental_income":         True,
        "rental_income_detail":  "12 months of lost rental income",
        "jewelry_cover":         True,
        "jewelry_detail":        "Scheduled jewelry and artwork: ₹10,00,000",
        "all_risk_contents":     True,
        "all_risk_detail":       "Accidental damage to all contents anywhere in India",
        "accidental_damage":     True,
        "accidental_damage_detail": "Accidental structural damage — falling objects, vehicle impact",

        "claim_process":         "Cashless preferred contractors + senior surveyor + digital tracking — 5 days",
        "claim_ratio":           "98.7%",
        "eligibility":           "All property types up to 55 years old",
        "benefits": [
            "₹1 Crore structure + ₹35L contents — full replacement cost",
            "All-risk contents cover — accidental damage anywhere in India",
            "Accidental structural damage included",
            "Personal liability: ₹25,00,000",
            "Jewelry and artwork: ₹10,00,000 scheduled",
            "12 months rental income protection",
            "Electrical machinery: ₹2,00,000 coverage",
            "Temporary accommodation: ₹25,000/week × 6 months",
            "Digital claim tracking with 5-day SLA",
        ],
        "exclusions": [
            "Pre-existing structural defects",
            "Properties primarily used for hazardous activities",
            "War, nuclear, and radioactive perils",
        ],
        "suitable_for": [
            "Large independent houses or luxury apartments",
            "Properties with high-value contents and artwork",
            "Owners seeking comprehensive all-risk protection",
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PREMIUM SEGMENT
    # ══════════════════════════════════════════════════════════════════════════

    "elite_property_shield": {
        "plan_id":               "AEG-PROP-007",
        "plan_name":             "Elite Property Shield",
        "segment":               "premium",

        "structure_coverage":    15_000_000,
        "structure_display":     "₹1,50,00,000",
        "contents_coverage":     5_000_000,
        "contents_display":      "₹50,00,000",
        "coverage_display":      "₹1.5 Crore Structure + ₹50L Contents",

        "premium_min":           18_000,
        "premium_max":           28_000,
        "premium_period":        "annual",

        "fire_cover":            True,
        "fire_detail":           "Agreed value basis — no depreciation deduction",
        "flood_cover":           True,
        "flood_detail":          "Full sum insured — structure and contents",
        "earthquake_cover":      True,
        "earthquake_detail":     "Full sum insured — agreed value basis",
        "storm_cover":           True,
        "storm_detail":          "All weather perils — cyclone, hail, flood, cloudburst",
        "theft_cover":           True,
        "theft_sublimit":        "₹8,00,000 (no sublimit on electronics)",
        "temp_accommodation":    True,
        "temp_accommodation_detail": "₹40,000/week up to 9 months",
        "electrical_cover":      True,
        "electrical_detail":     "₹5,00,000 — all electrical systems and smart home devices",
        "glass_cover":           True,
        "glass_detail":          "All glass, mirrors, ceramic, solar panels",
        "public_liability":      True,
        "public_liability_detail": "Third-party liability: ₹50,00,000",
        "rental_income":         True,
        "rental_income_detail":  "18 months of rental income protection",
        "jewelry_cover":         True,
        "jewelry_detail":        "Scheduled + unscheduled jewelry: ₹15,00,000",
        "all_risk_contents":     True,
        "all_risk_detail":       "All-risk contents worldwide while travelling",
        "accidental_damage":     True,
        "accidental_damage_detail": "Structural accidental damage including impact",
        "worldwide_contents":    True,
        "worldwide_detail":      "Personal belongings worldwide up to ₹10,00,000",
        "smart_home_cover":      True,
        "smart_home_detail":     "Smart devices, home automation, security systems",
        "emergency_assistance":  True,
        "emergency_detail":      "24/7 emergency helpline + on-site damage control team",

        "claim_process":         "Dedicated relationship manager + 24/7 helpline + 3-day settlement SLA",
        "claim_ratio":           "99.0%",
        "eligibility":           "All residential and commercial properties",
        "benefits": [
            "₹1.5 Crore structure + ₹50L contents on agreed value basis",
            "Worldwide contents cover: ₹10,00,000",
            "Smart home devices and automation systems covered",
            "Scheduled jewelry and unscheduled valuables: ₹15,00,000",
            "Third-party public liability: ₹50,00,000",
            "18 months rental income protection",
            "Electrical systems: ₹5,00,000",
            "24/7 emergency assistance + on-site response team",
            "Temporary accommodation: ₹40,000/week × 9 months",
            "Solar panels and glass: full replacement cost",
        ],
        "exclusions": [
            "Existing structural damage at policy inception",
            "Uninhabited properties beyond 60 days",
        ],
        "suitable_for": [
            "Premium villas and large independent houses",
            "Properties with smart home systems and solar installations",
            "High-value rental and investment properties",
        ],
    },

    "platinum_property_guard": {
        "plan_id":               "AEG-PROP-008",
        "plan_name":             "Platinum Property Guard",
        "segment":               "premium",

        "structure_coverage":    25_000_000,
        "structure_display":     "₹2,50,00,000",
        "contents_coverage":     7_500_000,
        "contents_display":      "₹75,00,000",
        "coverage_display":      "₹2.5 Crore Structure + ₹75L Contents",

        "premium_min":           28_000,
        "premium_max":           45_000,
        "premium_period":        "annual",

        "fire_cover":            True,
        "fire_detail":           "Agreed value — full reinstatement without depreciation",
        "flood_cover":           True,
        "flood_detail":          "Full sum insured — structure, contents, outbuildings",
        "earthquake_cover":      True,
        "earthquake_detail":     "Full sum insured including retaining walls and compound",
        "storm_cover":           True,
        "storm_detail":          "All weather perils + subsidence and heave",
        "theft_cover":           True,
        "theft_sublimit":        "₹12,00,000 (no sublimit on any item)",
        "temp_accommodation":    True,
        "temp_accommodation_detail": "₹60,000/week up to 12 months in equivalent standard",
        "electrical_cover":      True,
        "electrical_detail":     "₹10,00,000 — all electrical, solar, EV charger, generator",
        "glass_cover":           True,
        "glass_detail":          "All glass, mirrors, art glass — antique glass restoration",
        "public_liability":      True,
        "public_liability_detail": "Third-party liability: ₹1,00,00,000",
        "rental_income":         True,
        "rental_income_detail":  "24 months rental income + short-term rental liability",
        "jewelry_cover":         True,
        "jewelry_detail":        "Jewelry, art, antiques, collectibles: ₹15,00,000",
        "all_risk_contents":     True,
        "all_risk_detail":       "All-risk worldwide contents — no territorial restriction",
        "accidental_damage":     True,
        "accidental_damage_detail": "Accidental structural + outbuildings + pool",
        "worldwide_contents":    True,
        "worldwide_detail":      "Contents worldwide — no geographic limit",
        "smart_home_cover":      True,
        "smart_home_detail":     "Complete smart home ecosystem + EV charger",
        "emergency_assistance":  True,
        "emergency_detail":      "24/7 platinum hotline + dedicated property manager response",
        "legal_expenses":        True,
        "legal_detail":          "Property legal disputes: ₹5,00,000",
        "cyber_cover":           True,
        "cyber_detail":          "Home cyber protection (smart home breach): ₹5,00,000",
        "outbuildings":          True,
        "outbuildings_detail":   "Garden, pool, compound wall, annexe — included",

        "claim_process":         "White-glove claims with senior assessor + 48-hour on-site survey + 3-day settlement",
        "claim_ratio":           "99.3%",
        "eligibility":           "All property types including heritage and luxury",
        "benefits": [
            "₹2.5 Crore structure + ₹75L contents — agreed reinstatement value",
            "Outbuildings, swimming pool, garden included",
            "Legal expenses: ₹5,00,000",
            "Home cyber protection: ₹5,00,000",
            "Art, antiques, collectibles: ₹15,00,000",
            "EV charger and generator covered under electrical",
            "Third-party liability: ₹1 Crore",
            "Short-term rental liability included",
            "24 months rental income protection",
            "Worldwide all-risk contents coverage",
            "White-glove claims with 48-hour on-site assessor",
        ],
        "exclusions": [
            "Properties under active construction or renovation",
            "Government acquisition or compulsory purchase",
        ],
        "suitable_for": [
            "Luxury villas with pool, garden, and outbuildings",
            "Heritage properties and landmark homes",
            "High-value art and collectibles owners",
        ],
    },

    "ultimate_home_protection": {
        "plan_id":               "AEG-PROP-009",
        "plan_name":             "Ultimate Home Protection",
        "segment":               "premium",

        "structure_coverage":    50_000_000,
        "structure_display":     "₹5,00,00,000",
        "contents_coverage":     15_000_000,
        "contents_display":      "₹1,50,00,000",
        "coverage_display":      "₹5 Crore Structure + ₹1.5 Crore Contents",

        "premium_min":           45_000,
        "premium_max":           90_000,
        "premium_period":        "annual",

        "fire_cover":            True,
        "fire_detail":           "New-for-old replacement — bespoke valuation by private surveyor",
        "flood_cover":           True,
        "flood_detail":          "Full sum insured — all structures, outbuildings, grounds",
        "earthquake_cover":      True,
        "earthquake_detail":     "Full sum insured — bespoke structural engineering assessment",
        "storm_cover":           True,
        "storm_detail":          "All atmospheric perils including subsidence, heave, landslide",
        "theft_cover":           True,
        "theft_sublimit":        "No sublimit — full reinstatement value",
        "temp_accommodation":    True,
        "temp_accommodation_detail": "Equivalent luxury accommodation for 18 months",
        "electrical_cover":      True,
        "electrical_detail":     "₹25,00,000 — all electrical, solar farm, EV fleet charger, generator",
        "glass_cover":           True,
        "glass_detail":          "All glass including heritage stained glass — specialist restoration",
        "public_liability":      True,
        "public_liability_detail": "Third-party liability: ₹5,00,00,000 (5 Crore)",
        "rental_income":         True,
        "rental_income_detail":  "Full rental income protection — unlimited duration",
        "jewelry_cover":         True,
        "jewelry_detail":        "Jewelry, fine art, wine, watches — no cap (scheduled valuation)",
        "all_risk_contents":     True,
        "all_risk_detail":       "All-risk worldwide contents — zero territorial restriction",
        "accidental_damage":     True,
        "accidental_damage_detail": "All accidental damage — structure, contents, outbuildings, grounds",
        "worldwide_contents":    True,
        "worldwide_detail":      "Contents insured worldwide without limit",
        "smart_home_cover":      True,
        "smart_home_detail":     "Complete smart estate ecosystem + private server room",
        "emergency_assistance":  True,
        "emergency_detail":      "24/7 concierge response + private security on-site + helicopter access",
        "legal_expenses":        True,
        "legal_detail":          "Property legal and planning disputes: ₹25,00,000",
        "cyber_cover":           True,
        "cyber_detail":          "Estate cyber protection — smart systems, private network: ₹20,00,000",
        "outbuildings":          True,
        "outbuildings_detail":   "All outbuildings, pool, tennis court, stables, guest house",
        "private_surveyor":      True,
        "private_surveyor_detail": "Dedicated private surveyor team for annual valuation",

        "claim_process":         "Concierge claims team + private surveyor + 24-hour settlement SLA — zero out-of-pocket",
        "claim_ratio":           "99.6%",
        "eligibility":           "Any property — no age or type restriction",
        "benefits": [
            "₹5 Crore structure + ₹1.5 Crore contents — bespoke agreed value",
            "Jewelry, fine art, wine, watches — no value cap",
            "Private concierge claims team — 24-hour settlement SLA",
            "Third-party liability: ₹5 Crore",
            "Legal expenses: ₹25,00,000 (planning, disputes, eviction)",
            "Estate cyber protection: ₹20,00,000",
            "All outbuildings, pool, stables, guest house included",
            "Helicopter emergency access and private security response",
            "Annual bespoke valuation by private surveyor team",
            "No territorial restriction on contents",
            "Unlimited rental income protection",
        ],
        "exclusions": [
            "Purely commercial agricultural properties",
            "Pre-declared war zones",
        ],
        "suitable_for": [
            "Ultra-HNI estates, heritage properties, landmark homes",
            "Properties with irreplaceable art, antiques, or wine collections",
            "Owners who require zero compromise on coverage scope",
        ],
    },
}

# ── Quick lookup by segment ───────────────────────────────────────────────────

PLANS_BY_SEGMENT = {
    "budget":   ["home_essential", "home_secure",         "home_value"],
    "standard": ["home_protect",   "family_property_shield", "complete_property_care"],
    "premium":  ["elite_property_shield", "platinum_property_guard", "ultimate_home_protection"],
}
