"""
Aegis AI — Travel Insurance Plan Catalog
Complete internal plan registry for Ethan AI.
Nine plans across three traveller segments covering all trip types.
Premiums are indicative per-person rates for a 7–15 day trip; scale with duration and age.
"""

# ── Travel type classification ────────────────────────────────────────────────

TRAVEL_TYPE_KEYWORDS = {
    "adventure":     ["adventure", "trek", "trekking", "hiking", "ski", "skiing", "diving",
                      "scuba", "bungee", "paragliding", "mountaineering", "climbing",
                      "rafting", "surfing", "skydiving", "mountain biking", "safari"],
    "student":       ["student", "study abroad", "university", "college", "education",
                      "semester", "exchange program", "internship abroad"],
    "business":      ["business", "work trip", "conference", "corporate", "meeting",
                      "client visit", "trade show", "official travel"],
    "pilgrimage":    ["pilgrimage", "religious", "char dham", "hajj", "umrah", "kashi",
                      "tirumala", "amarnath", "vaishno devi", "kedarnath", "bodh gaya"],
    "senior":        ["senior", "elderly", "retired", "60+", "65+", "70+", "aged",
                      "60 years", "65 years", "70 years"],
    "group":         ["group", "tour group", "team trip", "friends group", "batch"],
    "frequent":      ["frequent", "multi-trip", "annual", "monthly travel", "multiple trips",
                      "year-round travel"],
    "family":        ["family", "kids", "children", "child", "son", "daughter",
                      "family vacation", "family holiday", "with spouse"],
    "domestic":      ["domestic", "within india", "indian cities", "india trip",
                      "rajasthan", "kerala", "goa", "manali", "shimla", "ooty",
                      "ladakh", "uttarakhand", "leh"],
    "international": ["international", "abroad", "overseas", "foreign", "europe",
                      "usa", "uk", "schengen", "dubai", "singapore", "thailand", "japan",
                      "australia", "canada", "maldives", "bali"],
}

# ── Segment thresholds (per-person insurance budget, INR, for a 7–15 day trip) ─

SEGMENT_THRESHOLDS = {
    "budget":   (0,      1_500),   # < ₹1,500/person/trip
    "standard": (1_500,  5_000),   # ₹1,500 – ₹5,000/person/trip
    "premium":  (5_000,  999_999), # > ₹5,000/person/trip
}

# ── Travel plan catalog ────────────────────────────────────────────────────────

TRAVEL_PLANS = {

    # ══════════════════════════════════════════════════════════════════════════
    # BUDGET SEGMENT
    # ══════════════════════════════════════════════════════════════════════════

    "travel_basic": {
        "plan_id":             "AEG-TRV-001",
        "plan_name":           "Travel Basic",
        "segment":             "budget",
        "travel_scope":        "Domestic + Short International",

        # Premium (per person, indicative for 7–15 days)
        "premium_min":         350,
        "premium_max":         650,
        "premium_note":        "Per person for 7–15 day trip; scales with duration and age",

        # Core covers
        "medical_cover":       "₹15,00,000",
        "medical_cover_amount": 1_500_000,
        "medical_cover_usd":   "$18,000",
        "emergency_evacuation": "₹10,00,000 (repatriation included)",
        "emergency_evac_amount": 1_000_000,
        "trip_cancellation":   "₹25,000 (per insured)",
        "trip_cancellation_amount": 25_000,
        "trip_delay":          "₹5,000 (delay > 12 hours)",
        "trip_delay_threshold": "12 hours",
        "lost_baggage":        "₹15,000",
        "lost_baggage_amount": 15_000,
        "baggage_delay":       "₹3,000 (delay > 24 hours)",
        "passport_loss":       "₹5,000",
        "personal_liability":  "₹1,00,000",
        "adventure_cover":     False,
        "adventure_detail":    "Not covered",
        "adventure_types":     [],
        "pre_existing_cover":  False,
        "pre_existing_detail": "Not covered",
        "flight_hijack":       False,
        "kidnap_cover":        False,
        "annual_multi_trip":   False,
        "schengen_compliant":  False,
        "schengen_note":       "Medical cover below Schengen minimum (€30,000 ≈ ₹27L)",
        "home_care":           False,
        "business_equipment":  False,
        "domestic_hospital":   "500+ network hospitals",
        "global_assistance":   "24/7 emergency helpline",

        "claim_process":       "Digital claim submission — 10 working days",
        "claim_ratio":         "96.5%",
        "eligibility":         "6 months to 70 years; single trip only",
        "benefits": [
            "Medical emergency cover: ₹15,00,000",
            "Emergency repatriation and evacuation: ₹10,00,000",
            "Trip cancellation cover: ₹25,000",
            "Lost baggage: ₹15,000",
            "24/7 emergency helpline",
            "No medical check required for travellers under 55",
        ],
        "exclusions": [
            "Adventure sports and high-risk activities",
            "Pre-existing medical conditions",
            "Not Schengen-compliant (below €30,000 medical requirement)",
            "Domestic travel medical cover excluded",
        ],
        "suitable_for": [
            "Budget domestic and short-haul international trips",
            "Young healthy travellers on a tight budget",
            "Southeast Asia and Gulf short trips",
        ],
    },

    "travel_smart": {
        "plan_id":             "AEG-TRV-002",
        "plan_name":           "Travel Smart",
        "segment":             "budget",
        "travel_scope":        "International",

        "premium_min":         650,
        "premium_max":         1_100,
        "premium_note":        "Per person for 7–15 days; higher for 60+ travellers",

        "medical_cover":       "₹30,00,000",
        "medical_cover_amount": 3_000_000,
        "medical_cover_usd":   "$36,000",
        "emergency_evacuation": "₹25,00,000 (repatriation + stretcher flight)",
        "emergency_evac_amount": 2_500_000,
        "trip_cancellation":   "₹50,000",
        "trip_cancellation_amount": 50_000,
        "trip_delay":          "₹8,000 (delay > 6 hours)",
        "trip_delay_threshold": "6 hours",
        "lost_baggage":        "₹25,000",
        "lost_baggage_amount": 25_000,
        "baggage_delay":       "₹6,000 (delay > 12 hours, essential purchase)",
        "passport_loss":       "₹10,000 (emergency documentation)",
        "personal_liability":  "₹2,50,000",
        "adventure_cover":     True,
        "adventure_detail":    "Basic adventure cover — trekking up to 3,500m, snorkeling",
        "adventure_types":     ["Trekking ≤3,500m", "Snorkeling", "Beach sports"],
        "pre_existing_cover":  False,
        "pre_existing_detail": "Not covered",
        "flight_hijack":       True,
        "flight_hijack_detail": "₹5,000 per hour (up to 12 hours)",
        "kidnap_cover":        False,
        "annual_multi_trip":   False,
        "schengen_compliant":  False,
        "schengen_note":       "Below Schengen minimum; upgrade to Travel Saver or above",
        "home_care":           False,
        "business_equipment":  False,
        "global_assistance":   "24/7 emergency helpline + partner hospitals in 60+ countries",

        "claim_process":       "Digital + cashless at partner hospitals — 8 working days",
        "claim_ratio":         "97.1%",
        "eligibility":         "6 months to 70 years; single trip",
        "benefits": [
            "Medical emergency: ₹30,00,000",
            "Emergency evacuation and repatriation: ₹25,00,000",
            "Flight hijacking compensation: ₹5,000/hour",
            "Basic adventure cover (trekking ≤3,500m, beach sports)",
            "Trip cancellation: ₹50,000",
            "Baggage delay cover: ₹6,000 for essential purchases",
            "24/7 assistance in 60+ countries",
        ],
        "exclusions": [
            "Pre-existing medical conditions",
            "Extreme adventure sports (skiing, diving > 10m, mountaineering)",
            "Not Schengen-compliant",
            "Travellers above 70 years",
        ],
        "suitable_for": [
            "Short international trips to Southeast Asia, Gulf, Sri Lanka",
            "Budget travellers wanting adventure basics",
            "Solo travellers aged 25–55",
        ],
    },

    "travel_saver": {
        "plan_id":             "AEG-TRV-003",
        "plan_name":           "Travel Saver",
        "segment":             "budget",
        "travel_scope":        "International (Schengen + worldwide)",

        "premium_min":         1_100,
        "premium_max":         1_500,
        "premium_note":        "Per person for 7–15 days; scales up for 60+ travellers",

        "medical_cover":       "₹50,00,000",
        "medical_cover_amount": 5_000_000,
        "medical_cover_usd":   "$60,000",
        "emergency_evacuation": "₹40,00,000 (full repatriation, medical escort)",
        "emergency_evac_amount": 4_000_000,
        "trip_cancellation":   "₹75,000",
        "trip_cancellation_amount": 75_000,
        "trip_delay":          "₹12,000 (delay > 6 hours)",
        "trip_delay_threshold": "6 hours",
        "lost_baggage":        "₹35,000",
        "lost_baggage_amount": 35_000,
        "baggage_delay":       "₹10,000 (delay > 8 hours, scheduled essentials)",
        "passport_loss":       "₹15,000 + emergency documentation assistance",
        "personal_liability":  "₹5,00,000",
        "adventure_cover":     True,
        "adventure_detail":    "Adventure cover — trekking up to 4,000m, snorkeling, kayaking",
        "adventure_types":     ["Trekking ≤4,000m", "Snorkeling", "Kayaking", "Cycling tours"],
        "pre_existing_cover":  False,
        "pre_existing_detail": "Basic cover for sudden acute episodes of declared conditions",
        "flight_hijack":       True,
        "flight_hijack_detail": "₹8,000 per hour (up to 12 hours)",
        "kidnap_cover":        False,
        "annual_multi_trip":   False,
        "schengen_compliant":  True,
        "schengen_note":       "Schengen-compliant — exceeds €30,000 minimum requirement",
        "home_care":           False,
        "business_equipment":  False,
        "global_assistance":   "24/7 emergency helpline + cashless at 3,000+ global partner hospitals",

        "claim_process":       "Cashless at partner hospitals + digital reimbursement — 7 days",
        "claim_ratio":         "97.6%",
        "eligibility":         "3 months to 70 years; single trip",
        "benefits": [
            "Medical emergency: ₹50,00,000 (Schengen-compliant)",
            "Emergency evacuation + medical escort: ₹40,00,000",
            "Trip cancellation: ₹75,000",
            "Baggage delay essentials purchase: ₹10,000",
            "Adventure cover — trekking up to 4,000m",
            "Flight hijacking: ₹8,000/hour",
            "Cashless at 3,000+ global hospitals",
            "Emergency passport assistance",
        ],
        "exclusions": [
            "Pre-existing conditions beyond acute episodes",
            "High-altitude mountaineering (>4,000m)",
            "Extreme sports (bungee, sky diving, skiing)",
            "Travellers above 70",
        ],
        "suitable_for": [
            "Europe and Schengen travel needing visa compliance",
            "Budget-conscious international travellers",
            "Light adventure trips — Nepal, Bhutan, Europe hiking",
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # STANDARD SEGMENT
    # ══════════════════════════════════════════════════════════════════════════

    "travel_shield": {
        "plan_id":             "AEG-TRV-004",
        "plan_name":           "Travel Shield",
        "segment":             "standard",
        "travel_scope":        "Worldwide",

        "premium_min":         1_500,
        "premium_max":         2_800,
        "premium_note":        "Per person for 7–15 days; family discounts available",

        "medical_cover":       "₹75,00,000",
        "medical_cover_amount": 7_500_000,
        "medical_cover_usd":   "$90,000",
        "emergency_evacuation": "₹60,00,000 (air ambulance + repatriation)",
        "emergency_evac_amount": 6_000_000,
        "trip_cancellation":   "₹1,00,000",
        "trip_cancellation_amount": 100_000,
        "trip_delay":          "₹15,000 (delay > 4 hours)",
        "trip_delay_threshold": "4 hours",
        "lost_baggage":        "₹50,000",
        "lost_baggage_amount": 50_000,
        "baggage_delay":       "₹15,000 (delay > 6 hours)",
        "passport_loss":       "₹20,000 + embassy coordination",
        "personal_liability":  "₹10,00,000",
        "adventure_cover":     True,
        "adventure_detail":    "Moderate adventure — trekking up to 5,000m, skiing, scuba diving (to 30m)",
        "adventure_types":     ["Trekking ≤5,000m", "Skiing (piste only)", "Scuba diving ≤30m",
                                "Kayaking", "Bungee jumping", "Cycling", "White water rafting (Grade ≤4)"],
        "pre_existing_cover":  True,
        "pre_existing_detail": "Declared stable pre-existing conditions covered for emergency treatment",
        "flight_hijack":       True,
        "flight_hijack_detail": "₹10,000 per hour (up to 24 hours)",
        "kidnap_cover":        False,
        "annual_multi_trip":   False,
        "schengen_compliant":  True,
        "schengen_note":       "Schengen-compliant — exceeds €30,000 minimum by 3x",
        "home_care":           True,
        "home_care_detail":    "Home burglary cover while travelling: ₹50,000",
        "business_equipment":  False,
        "global_assistance":   "24/7 assistance + cashless at 7,000+ partner hospitals globally",

        "claim_process":       "Cashless at partner hospitals + dedicated claims team — 5 days",
        "claim_ratio":         "98.1%",
        "eligibility":         "3 months to 75 years; single trip or short-term",
        "benefits": [
            "Medical emergency: ₹75,00,000 ($90,000)",
            "Air ambulance + repatriation: ₹60,00,000",
            "Declared pre-existing conditions covered for emergencies",
            "Adventure cover — trekking ≤5,000m, skiing, diving to 30m",
            "Trip cancellation: ₹1,00,000",
            "Home burglary cover while travelling: ₹50,000",
            "Baggage delay: ₹15,000 for emergency purchases",
            "Flight hijacking: ₹10,000/hour",
            "Cashless at 7,000+ hospitals worldwide",
        ],
        "exclusions": [
            "Undeclared pre-existing conditions",
            "Extreme mountaineering above 5,000m",
            "Motor racing, base jumping, skydiving (unless Elite+ plan)",
        ],
        "suitable_for": [
            "Solo or couple international travel — USA, Europe, Japan, Australia",
            "Moderate adventure travellers — Nepal, Switzerland, New Zealand",
            "Travellers with declared health conditions",
        ],
    },

    "family_travel_protect": {
        "plan_id":             "AEG-TRV-005",
        "plan_name":           "Family Travel Protect",
        "segment":             "standard",
        "travel_scope":        "Worldwide — Family Cover",

        "premium_min":         2_500,
        "premium_max":         4_500,
        "premium_note":        "Per family (2 adults + up to 3 children); children under 6 free",

        "medical_cover":       "₹75,00,000 per person",
        "medical_cover_amount": 7_500_000,
        "medical_cover_usd":   "$90,000 per person",
        "emergency_evacuation": "₹60,00,000 per person (family repatriation coordination)",
        "emergency_evac_amount": 6_000_000,
        "trip_cancellation":   "₹1,50,000 (family aggregate)",
        "trip_cancellation_amount": 150_000,
        "trip_delay":          "₹20,000 family aggregate (delay > 4 hours)",
        "trip_delay_threshold": "4 hours",
        "lost_baggage":        "₹60,000 family aggregate (₹20,000 per child sublimit)",
        "lost_baggage_amount": 60_000,
        "baggage_delay":       "₹18,000 family (delay > 6 hours, children's essentials)",
        "passport_loss":       "₹25,000 family (embassy coordination included)",
        "personal_liability":  "₹15,00,000 (family aggregate)",
        "adventure_cover":     True,
        "adventure_detail":    "Family adventure — moderate sports for adults; safe activities for children",
        "adventure_types":     ["Adults: Trekking ≤5,000m, skiing, rafting", "Children: Cycling, beach sports, zip-lining"],
        "pre_existing_cover":  True,
        "pre_existing_detail": "Declared conditions covered; child congenital conditions covered",
        "flight_hijack":       True,
        "flight_hijack_detail": "₹8,000 per person per hour (family)",
        "kidnap_cover":        True,
        "kidnap_detail":       "₹5,00,000 family (high-risk destination cover)",
        "annual_multi_trip":   False,
        "schengen_compliant":  True,
        "schengen_note":       "Fully Schengen-compliant for all family members",
        "home_care":           True,
        "home_care_detail":    "Home burglary during travel: ₹75,000 + domestic help arrangement",
        "business_equipment":  False,
        "global_assistance":   "24/7 family assistance + multilingual support + paediatric helpline",

        "claim_process":       "Family claim coordinator + cashless worldwide — 5 days",
        "claim_ratio":         "98.3%",
        "eligibility":         "Children from 6 weeks; adults to 75 years; family of up to 6",
        "benefits": [
            "₹75L medical per person — entire family covered",
            "Children under 6 years: no additional premium",
            "Child congenital conditions covered",
            "Family trip cancellation: ₹1,50,000",
            "Kidnap and ransom cover: ₹5,00,000 (high-risk zones)",
            "Paediatric emergency helpline — 24/7",
            "Family baggage: ₹60,000 with per-child sublimits",
            "Home burglary during travel: ₹75,000",
            "Multilingual emergency assistance",
        ],
        "exclusions": [
            "Children travelling without at least one parent",
            "Pre-existing conditions not declared at inception",
            "Extreme sports for children under 12",
        ],
        "suitable_for": [
            "Families with young children travelling internationally",
            "Family holidays to Europe, USA, Southeast Asia",
            "Families with children with health conditions",
        ],
    },

    "complete_traveller": {
        "plan_id":             "AEG-TRV-006",
        "plan_name":           "Complete Traveller",
        "segment":             "standard",
        "travel_scope":        "Worldwide — All Trip Types",

        "premium_min":         3_000,
        "premium_max":         5_000,
        "premium_note":        "Per person for 7–15 days; senior and adventure loading applies",

        "medical_cover":       "₹1,50,00,000",
        "medical_cover_amount": 15_000_000,
        "medical_cover_usd":   "$1,80,000",
        "emergency_evacuation": "₹1,00,00,000 (private air ambulance eligible)",
        "emergency_evac_amount": 10_000_000,
        "trip_cancellation":   "₹2,00,000",
        "trip_cancellation_amount": 200_000,
        "trip_delay":          "₹25,000 (delay > 3 hours)",
        "trip_delay_threshold": "3 hours",
        "lost_baggage":        "₹75,000",
        "lost_baggage_amount": 75_000,
        "baggage_delay":       "₹20,000 (delay > 6 hours)",
        "passport_loss":       "₹35,000 + emergency replacement assistance",
        "personal_liability":  "₹20,00,000",
        "adventure_cover":     True,
        "adventure_detail":    "Extended adventure — all standard and moderate extreme sports",
        "adventure_types":     ["Trekking ≤5,500m", "Skiing", "Scuba diving ≤40m",
                                "Bungee jumping", "Paragliding", "Mountain biking",
                                "White water rafting (any grade)", "Zip-lining"],
        "pre_existing_cover":  True,
        "pre_existing_detail": "All declared stable conditions fully covered for emergency treatment abroad",
        "flight_hijack":       True,
        "flight_hijack_detail": "₹12,000 per hour (up to 24 hours)",
        "kidnap_cover":        False,
        "annual_multi_trip":   False,
        "schengen_compliant":  True,
        "schengen_note":       "Schengen-compliant — exceeds minimum by 6x",
        "home_care":           True,
        "home_care_detail":    "Home burglary during travel: ₹1,00,000",
        "business_equipment":  True,
        "business_equipment_detail": "Business equipment and laptop cover: ₹50,000",
        "pet_care":            True,
        "pet_care_detail":     "Emergency pet care during travel: ₹10,000",
        "global_assistance":   "24/7 premium assistance + cashless at 10,000+ partner hospitals",

        "claim_process":       "Cashless worldwide + dedicated account manager — 4 days",
        "claim_ratio":         "98.6%",
        "eligibility":         "6 months to 75 years; single trip",
        "benefits": [
            "Medical emergency: ₹1,50,00,000 ($1,80,000)",
            "Private air ambulance option: ₹1 Crore",
            "Extended adventure sports including paragliding and bungee",
            "Business equipment cover: ₹50,000",
            "Emergency pet care: ₹10,000",
            "Trip cancellation: ₹2,00,000",
            "Home burglary protection: ₹1,00,000",
            "All declared pre-existing conditions covered",
            "3-hour delay compensation trigger",
            "Personal liability: ₹20,00,000",
        ],
        "exclusions": [
            "Mountaineering above 5,500m without guide",
            "Motor racing and competitive extreme sports",
            "Undeclared pre-existing conditions",
        ],
        "suitable_for": [
            "Experienced international travellers with broad adventure plans",
            "Business + leisure travellers",
            "Travellers with declared health conditions seeking full coverage",
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PREMIUM SEGMENT
    # ══════════════════════════════════════════════════════════════════════════

    "elite_traveller": {
        "plan_id":             "AEG-TRV-007",
        "plan_name":           "Elite Traveller",
        "segment":             "premium",
        "travel_scope":        "Worldwide Premium",

        "premium_min":         5_500,
        "premium_max":         8_500,
        "premium_note":        "Per person for 7–15 days; senior and adventure loading applies",

        "medical_cover":       "₹3,00,00,000",
        "medical_cover_amount": 30_000_000,
        "medical_cover_usd":   "$3,60,000",
        "emergency_evacuation": "₹2,00,00,000 (private jet repatriation eligible)",
        "emergency_evac_amount": 20_000_000,
        "trip_cancellation":   "₹3,00,000",
        "trip_cancellation_amount": 300_000,
        "trip_delay":          "₹40,000 (delay > 2 hours — premium lounge access)",
        "trip_delay_threshold": "2 hours",
        "lost_baggage":        "₹1,00,000",
        "lost_baggage_amount": 100_000,
        "baggage_delay":       "₹30,000 (delay > 4 hours — luxury brand replacement)",
        "passport_loss":       "₹50,000 + 24/7 VIP embassy coordination",
        "personal_liability":  "₹50,00,000",
        "adventure_cover":     True,
        "adventure_detail":    "Full adventure — all sports including high-altitude mountaineering",
        "adventure_types":     ["Mountaineering ≤6,000m", "Extreme skiing (off-piste)",
                                "Scuba diving ≤50m", "Bungee", "Paragliding", "Skydiving",
                                "White water rafting (all grades)", "Mountain biking (downhill)",
                                "Safari with walking trails"],
        "pre_existing_cover":  True,
        "pre_existing_detail": "All declared conditions — no waiting period — immediate cover",
        "flight_hijack":       True,
        "flight_hijack_detail": "₹20,000 per hour (up to 48 hours)",
        "kidnap_cover":        True,
        "kidnap_detail":       "₹10,00,000 kidnap and ransom",
        "annual_multi_trip":   True,
        "annual_detail":       "Annual multi-trip option — unlimited trips, 45 days max per trip",
        "schengen_compliant":  True,
        "schengen_note":       "Schengen-compliant — exceeds minimum by 12x",
        "home_care":           True,
        "home_care_detail":    "Luxury home care during travel: ₹1,50,000",
        "business_equipment":  True,
        "business_equipment_detail": "Business equipment + laptop + camera: ₹1,00,000",
        "golf_equipment":      True,
        "golf_detail":         "Golf equipment cover: ₹50,000",
        "concierge":           True,
        "concierge_detail":    "24/7 travel concierge — rebooking, hotel upgrades, dining reservations",
        "global_assistance":   "24/7 dedicated concierge + cashless at 12,000+ partner hospitals",

        "claim_process":       "Priority cashless + relationship manager + 48-hour settlement",
        "claim_ratio":         "99.0%",
        "eligibility":         "6 months to 80 years; single or annual multi-trip",
        "benefits": [
            "Medical emergency: ₹3,00,00,000 ($3,60,000)",
            "Private jet repatriation option: ₹2 Crore",
            "Annual multi-trip option — unlimited travel in the year",
            "Full extreme adventure cover including skydiving",
            "Kidnap and ransom: ₹10,00,000",
            "Golf equipment: ₹50,000",
            "2-hour delay trigger with lounge access",
            "24/7 travel concierge (rebooking, upgrades, dining)",
            "Luxury baggage delay replacement: ₹30,000",
            "Home care during travel: ₹1,50,000",
        ],
        "exclusions": [
            "Mountaineering above 6,000m without certified guide",
            "Drug or alcohol-related emergencies",
            "Cosmetic travel (surgery tourism)",
        ],
        "suitable_for": [
            "Frequent premium international travellers",
            "Adventure seekers — Everest base camp, extreme skiing",
            "Business travellers with high-value equipment",
        ],
    },

    "platinum_global": {
        "plan_id":             "AEG-TRV-008",
        "plan_name":           "Platinum Global",
        "segment":             "premium",
        "travel_scope":        "Worldwide — No Restrictions",

        "premium_min":         8_500,
        "premium_max":         14_000,
        "premium_note":        "Per person for 7–15 days; annual option available",

        "medical_cover":       "₹5,00,00,000",
        "medical_cover_amount": 50_000_000,
        "medical_cover_usd":   "$6,00,000",
        "emergency_evacuation": "₹4,00,00,000 (helicopter + private jet, global)",
        "emergency_evac_amount": 40_000_000,
        "trip_cancellation":   "₹5,00,000",
        "trip_cancellation_amount": 500_000,
        "trip_delay":          "₹60,000 (delay > 2 hours — business class upgrade credit)",
        "trip_delay_threshold": "2 hours",
        "lost_baggage":        "₹1,50,000",
        "lost_baggage_amount": 150_000,
        "baggage_delay":       "₹50,000 (delay > 4 hours — luxury purchase authorized)",
        "passport_loss":       "₹75,000 + white-glove embassy fast-track service",
        "personal_liability":  "₹1,00,00,000",
        "adventure_cover":     True,
        "adventure_detail":    "Comprehensive adventure — mountaineering up to 7,000m, all extreme sports",
        "adventure_types":     ["Mountaineering ≤7,000m", "Heli-skiing", "Cave diving",
                                "Skydiving (certified)", "Free climbing", "Motorized water sports",
                                "Polo", "All competition sports except motor racing"],
        "pre_existing_cover":  True,
        "pre_existing_detail": "All pre-existing conditions — declared and undeclared acute episodes",
        "flight_hijack":       True,
        "flight_hijack_detail": "₹30,000 per hour unlimited duration",
        "kidnap_cover":        True,
        "kidnap_detail":       "₹15,00,000 kidnap and ransom — global",
        "annual_multi_trip":   True,
        "annual_detail":       "Annual option — unlimited trips, 90 days max per trip globally",
        "schengen_compliant":  True,
        "schengen_note":       "Schengen-compliant — exceeds minimum by 20x",
        "home_care":           True,
        "home_care_detail":    "Estate care during travel: ₹2,50,000",
        "business_equipment":  True,
        "business_equipment_detail": "All business and creative equipment: ₹2,00,000",
        "concierge":           True,
        "concierge_detail":    "Platinum 24/7 concierge — private transfers, priority medical access, hotel",
        "social_media_liability": True,
        "social_media_detail": "Online reputation management during crises: ₹2,50,000",
        "global_assistance":   "Dedicated platinum handler + cashless at 15,000+ hospitals worldwide",

        "claim_process":       "White-glove cashless + platinum claims handler + 24-hour settlement SLA",
        "claim_ratio":         "99.3%",
        "eligibility":         "Any age; single or annual multi-trip",
        "benefits": [
            "Medical emergency: ₹5,00,00,000 ($6,00,000)",
            "Helicopter + private jet evacuation: ₹4 Crore",
            "Annual multi-trip — up to 90 days per trip",
            "All pre-existing conditions — acute episodes covered without declaration",
            "Mountaineering up to 7,000m",
            "Kidnap and ransom: ₹15,00,000 globally",
            "Business class upgrade credit for delays",
            "Social media liability protection: ₹2,50,000",
            "Platinum 24/7 concierge — transfers, accommodation, medical priority",
            "24-hour claims settlement SLA",
        ],
        "exclusions": [
            "Declared mountaineering above 7,000m requires endorsement",
            "War and active military conflict zones",
            "Drug abuse-related incidents",
        ],
        "suitable_for": [
            "HNI frequent global travellers",
            "Expedition-level adventure travellers",
            "C-suite executives with complex international schedules",
        ],
    },

    "executive_world_cover": {
        "plan_id":             "AEG-TRV-009",
        "plan_name":           "Executive World Cover",
        "segment":             "premium",
        "travel_scope":        "Unlimited Worldwide",

        "premium_min":         14_000,
        "premium_max":         28_000,
        "premium_note":        "Per person for 7–15 days; annual option ₹50,000–₹1,20,000",

        "medical_cover":       "Unlimited",
        "medical_cover_amount": 999_999_999,
        "medical_cover_usd":   "Unlimited",
        "emergency_evacuation": "Unlimited (private medical jet, physician escort, ICU-in-air)",
        "emergency_evac_amount": 999_999_999,
        "trip_cancellation":   "₹10,00,000",
        "trip_cancellation_amount": 1_000_000,
        "trip_delay":          "₹1,00,000 (any delay > 1 hour — VIP ground transfer arranged)",
        "trip_delay_threshold": "1 hour",
        "lost_baggage":        "₹3,00,000 (luxury luggage + replacement)",
        "lost_baggage_amount": 300_000,
        "baggage_delay":       "₹1,00,000 (immediate luxury essentials authorized)",
        "passport_loss":       "₹1,00,000 + diplomatic emergency assistance",
        "personal_liability":  "₹2,00,00,000",
        "adventure_cover":     True,
        "adventure_detail":    "All activities worldwide — no exclusion on sports or altitude",
        "adventure_types":     ["All sports globally", "Mountaineering — no altitude limit",
                                "Motor racing (non-professional)", "All competitive sports",
                                "Expedition activities"],
        "pre_existing_cover":  True,
        "pre_existing_detail": "All conditions covered — no declaration required — day 1 cover",
        "flight_hijack":       True,
        "flight_hijack_detail": "₹50,000 per hour — unlimited duration",
        "kidnap_cover":        True,
        "kidnap_detail":       "₹50,00,000 kidnap, ransom and extortion — worldwide",
        "annual_multi_trip":   True,
        "annual_detail":       "Annual — unlimited trips, unlimited days per trip",
        "schengen_compliant":  True,
        "schengen_note":       "Schengen-compliant — unlimited medical cover",
        "home_care":           True,
        "home_care_detail":    "White-glove estate management during travel — no cap",
        "business_equipment":  True,
        "business_equipment_detail": "All business assets — no cap (declared schedule)",
        "director_liability":  True,
        "director_detail":     "Director and officer liability during travel: ₹10,00,000",
        "business_interruption": True,
        "business_interruption_detail": "Business interruption cover: ₹5,00,000",
        "concierge":           True,
        "concierge_detail":    "White-glove executive travel concierge — private jet booking, security escort, crisis management",
        "global_assistance":   "Dedicated executive travel team + any hospital in the world — cashless guaranteed",

        "claim_process":       "Concierge claims team — pre-authorized cashless at any hospital — zero paperwork",
        "claim_ratio":         "99.6%",
        "eligibility":         "Any age — no restrictions; annual unlimited trips",
        "benefits": [
            "Unlimited medical cover — anywhere in the world",
            "Unlimited emergency evacuation — private medical jet",
            "No pre-existing condition declaration required",
            "All sports and activities — no exclusions",
            "Kidnap, ransom and extortion: ₹50,00,000",
            "Director and officer liability: ₹10,00,000",
            "Business interruption: ₹5,00,000",
            "Annual unlimited trips — no per-trip day limit",
            "1-hour delay trigger with VIP ground transfer",
            "Luxury luggage replacement: ₹3,00,000",
            "White-glove executive concierge — crisis, security, travel management",
            "Zero paperwork — pre-authorized cashless at any hospital globally",
        ],
        "exclusions": [
            "Deliberate self-harm",
            "Active military service or combat zones",
            "Illegal activities in destination country",
        ],
        "suitable_for": [
            "Ultra-HNI executives and board members with global travel",
            "Celebrities and public figures needing discreet assistance",
            "Expedition leaders requiring unlimited medical and adventure cover",
        ],
    },
}

# ── Quick lookup by segment ───────────────────────────────────────────────────

PLANS_BY_SEGMENT = {
    "budget":   ["travel_basic",   "travel_smart",      "travel_saver"],
    "standard": ["travel_shield",  "family_travel_protect", "complete_traveller"],
    "premium":  ["elite_traveller","platinum_global",   "executive_world_cover"],
}
