"use client";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { usePurchase, extractPremiumAmount, calculateGST, getExpiryDate } from "@/context/PurchaseContext";
import { resolveAdvisorName } from "@/lib/advisors";
import {
  ShieldCheck, Download, CreditCard, LayoutDashboard,
  MessageSquare, Calendar, User, IndianRupee, Hash, Star,
  Sparkles,
} from "lucide-react";

function InfoCard({ label, value, icon: Icon, accent }: {
  label: string; value: string; icon: React.ComponentType<{ className?: string }>; accent?: boolean;
}) {
  return (
    <div className="flex items-start gap-3 p-3.5 rounded-xl border border-white/5 bg-white/[0.02]">
      <div className="w-8 h-8 rounded-lg bg-cyan-500/10 flex items-center justify-center flex-shrink-0">
        <Icon className="w-4 h-4 text-cyan-400" />
      </div>
      <div className="min-w-0">
        <p className="text-xs text-white/35 mb-0.5">{label}</p>
        <p className={`text-sm font-semibold break-all ${accent ? "text-cyan-300" : "text-white"}`}>{value}</p>
      </div>
    </div>
  );
}

export default function SuccessPage() {
  const router = useRouter();
  const { state, resetPurchase } = usePurchase();
  const plan = state.planData;
  const c = state.customerDetails;

  const basePremium = extractPremiumAmount(plan?.premium || "850");
  const gst = calculateGST(basePremium);
  const discount = state.couponDiscount > 0 ? Math.round(basePremium * state.couponDiscount / 100) : 0;
  const total = basePremium + gst - discount;
  const startDate = state.startDate || new Date().toISOString().split("T")[0];
  const expiryDate = getExpiryDate(startDate);
  // The receipt names the advisor who owns this policy's category. Fall back to
  // that category's advisor — not a hardcoded Sarah — so a motor/travel/home
  // receipt never mislabels Alex/Ethan/Emma as the health advisor.
  const advisorName = state.advisorName || resolveAdvisorName(plan?.category ?? "", "Sarah AI");

  const formatDate = (d: string) =>
    new Date(d).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

  const handleDownloadPDF = () => {
    const content = `
AEGIS INSURANCE - POLICY DOCUMENT
===================================
Policy Number : ${state.policyNumber}
Policy ID     : ${state.policyId}
Plan Name     : ${plan?.planName}
Category      : ${plan?.category?.toUpperCase()}
Coverage      : ${plan?.coverage}
Premium       : ₹${total.toLocaleString()}/month
Start Date    : ${formatDate(startDate)}
Expiry Date   : ${formatDate(expiryDate)}
Advisor       : ${advisorName}
Insured       : ${c ? `${c.firstName} ${c.lastName}` : "Customer"}
Nominee       : ${c ? `${c.nomineeName} (${c.nomineeRelation})` : "—"}
===================================
This is a demo policy document generated by Aegis AI.
IRDAI Registration: Demo Mode
    `.trim();
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${state.policyNumber || "policy"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadCard = () => {
    const content = `
╔══════════════════════════════════════╗
║          AEGIS INSURANCE CARD        ║
╠══════════════════════════════════════╣
║ Name    : ${(c ? `${c.firstName} ${c.lastName}` : "Customer").padEnd(27)}║
║ Policy  : ${(state.policyNumber || "—").padEnd(27)}║
║ Plan    : ${(plan?.planName || "—").padEnd(27)}║
║ Valid   : ${formatDate(startDate).padEnd(27)}║
║ Expires : ${formatDate(expiryDate).padEnd(27)}║
║ Advisor : ${advisorName.padEnd(27)}║
╚══════════════════════════════════════╝
    `.trim();
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${state.policyNumber || "insurance"}-card.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!plan) {
    router.push("/advisor");
    return null;
  }

  return (
    <div className="space-y-6">
      {/* Hero */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="rounded-2xl border border-emerald-500/20 bg-gradient-to-br from-emerald-500/10 to-cyan-500/5 p-8 text-center space-y-4"
      >
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ type: "spring", stiffness: 200, delay: 0.1 }}
          className="w-20 h-20 rounded-full bg-emerald-500/20 border-2 border-emerald-400/30 flex items-center justify-center mx-auto"
        >
          <ShieldCheck className="w-10 h-10 text-emerald-400" />
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <div className="flex items-center justify-center gap-2 mb-2">
            <Sparkles className="w-4 h-4 text-yellow-400" />
            <span className="text-yellow-400 text-xs font-semibold uppercase tracking-widest">Policy Issued</span>
            <Sparkles className="w-4 h-4 text-yellow-400" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-white">Welcome to Aegis!</h1>
          <p className="text-emerald-300/70 text-sm mt-1">
            Your insurance policy is active and documents have been sent to your email.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white/5 border border-white/10"
        >
          <Hash className="w-3.5 h-3.5 text-cyan-400" />
          <span className="text-white font-mono text-sm font-semibold">{state.policyNumber || "—"}</span>
        </motion.div>
      </motion.div>

      {/* Policy Details Grid */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.15 }}
        className="rounded-2xl border border-white/5 bg-white/[0.02] p-5 space-y-3"
      >
        <h3 className="text-sm font-semibold text-white pb-2 border-b border-white/5 flex items-center gap-2">
          <Star className="w-4 h-4 text-yellow-400" /> Policy Summary
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
          <InfoCard label="Policy Number"  value={state.policyNumber || "—"} icon={Hash} accent />
          <InfoCard label="Policy ID"      value={state.policyId || "—"} icon={Hash} />
          <InfoCard label="Plan"           value={plan.planName} icon={ShieldCheck} accent />
          <InfoCard label="Coverage"       value={plan.coverage} icon={ShieldCheck} />
          <InfoCard label="Monthly Premium" value={`₹${total.toLocaleString()}`} icon={IndianRupee} accent />
          <InfoCard label="Start Date"     value={formatDate(startDate)} icon={Calendar} />
          <InfoCard label="Expiry Date"    value={formatDate(expiryDate)} icon={Calendar} accent />
          <InfoCard label="Advisor"        value={advisorName} icon={MessageSquare} />
        </div>
        {c && (
          <InfoCard
            label="Insured / Nominee"
            value={`${c.firstName} ${c.lastName} · ${c.nomineeName} (${c.nomineeRelation})`}
            icon={User}
          />
        )}
      </motion.div>

      {/* Download Buttons */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="grid grid-cols-1 sm:grid-cols-2 gap-3"
      >
        <button onClick={handleDownloadPDF}
          className="flex items-center justify-center gap-2.5 py-3.5 rounded-xl border border-cyan-500/25
            bg-cyan-500/10 text-cyan-300 text-sm font-semibold hover:bg-cyan-500/20 transition-colors">
          <Download className="w-4 h-4" /> Download Policy PDF
        </button>
        <button onClick={handleDownloadCard}
          className="flex items-center justify-center gap-2.5 py-3.5 rounded-xl border border-purple-500/25
            bg-purple-500/10 text-purple-300 text-sm font-semibold hover:bg-purple-500/20 transition-colors">
          <CreditCard className="w-4 h-4" /> Download Insurance Card
        </button>
      </motion.div>

      {/* Email / SMS notice */}
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.25 }}
        className="rounded-xl border border-white/5 bg-white/[0.02] p-4 text-center"
      >
        <p className="text-xs text-white/35">
          Policy documents and e-insurance card have been sent to{" "}
          <span className="text-white/55">{c?.email || "your registered email"}</span>
          {" "}and a confirmation SMS to{" "}
          <span className="text-white/55">{c?.mobile ? `+91 ${c.mobile}` : "your mobile"}</span>.
        </p>
      </motion.div>

      {/* Navigation */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
        className="flex flex-col sm:flex-row gap-3"
      >
        <button
          onClick={() => router.push("/advisor")}
          className="flex-1 py-3 rounded-xl border border-white/10 text-white/50 text-sm font-medium
            hover:border-white/20 hover:text-white/70 transition-colors flex items-center justify-center gap-2"
        >
          <MessageSquare className="w-4 h-4" /> Contact Advisor
        </button>
        <button
          onClick={() => { resetPurchase(); router.push("/consumer-dashboard"); }}
          className="flex-1 py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 text-white font-semibold text-sm
            flex items-center justify-center gap-2 hover:shadow-lg hover:shadow-cyan-500/25 transition-all"
        >
          <LayoutDashboard className="w-4 h-4" /> View Dashboard
        </button>
      </motion.div>
    </div>
  );
}
